server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://64.120.89.44:3100/loki/api/v1/push

scrape_configs:
  - job_name: admi-api-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: admi-api-dev
          __path__: /mnt/logs/admi-api-dev/*.log

  - job_name: dpwd-api-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: dpwd-api-dev
          __path__: /mnt/logs/dpwd-api-dev/*.log

  - job_name: gp-api-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: gp-api-dev
          __path__: /mnt/logs/gp-api-dev/*.log

  - job_name: log-api-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: log-api-dev
          __path__: /mnt/logs/log-api-dev/*.log

  - job_name: master-api-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: master-api-dev
          __path__: /mnt/logs/master-api-dev/*.log

  - job_name: memo-api-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: memo-api-dev
          __path__: /mnt/logs/memo-api-dev/*.log
    
  - job_name: report-api-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: report-api-dev
          __path__: /mnt/logs/report-api-dev/*.log

  - job_name: cronjob-api-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: cronjob-api-dev
          __path__: /mnt/logs/cronjob-api-dev/*.log
      
  - job_name: user-api-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: user-api-dev
          __path__: /mnt/logs/user-api-dev/*.log
